### ISSUE TITLE
Could you let UDV remember window size and position?

### ISSUE THREAD

**Issue by bsto** [vurdalakov/usbdevices#2]
Whenever I start USB Device Viewer it starts at a pre-defined position with a small size.

I always have to move and resize it manually.

Could the auther let the tool auto-rememeber (and restore) the window size and position at exit?

Thank you

**Comment by vurdalakov** [comment]
Please try version 1.02 from the front page:
https://github.com/vurdalakov/usbdevices

**Comment by bsto** [comment]
works
Thank you
